project:
  type: website
  output-dir: docs

website:
  title: "KPZ"
  navbar:
    left:
      - href: index.qmd
        text: Описание
      - href: install.qmd
        text: Инструкция
      - text: Функции
        menu:
          - text: Фаза ML
            href: ML.qmd
          - text: Фаза ETL
            href: ETL.qmd
          - text: Сервер
            href: server.qmd
      - href: example.qmd
        text: Пример использования

format:
  html:
    theme: solar
    css: styles.css
    toc: true
    toc-title: "Навигация по странице"

editor: visual

